// C:\faiq\skripsi\skripsigb01\app\components\shared\UIStyles.ts

export const sharedStyles = {
  pageWrapper: {
    padding: "32px 40px",
    width: "100%",
    boxSizing: "border-box" as const,
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  headerContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 32,
    flexWrap: "wrap" as const,
    gap: 16,
  },
  pageTitle: {
    margin: 0,
    fontSize: 28,
    fontWeight: 800,
    color: "#0f172a",
    letterSpacing: -0.5,
  },
  pageSubtitle: {
    margin: "6px 0 0",
    fontSize: 14,
    color: "#64748b",
  },
  btnBase: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "6px 12px",
    fontSize: 12.5,
    fontWeight: 600,
    borderRadius: 8,
    border: "1.5px solid",
    cursor: "pointer",
    transition: "all 0.15s ease",
    fontFamily: "inherit",
  },
  btnPrimary: {
    padding: "9px 20px",
    background: "#0f172a",
    borderColor: "#0f172a",
    color: "#fff",
    fontSize: 13.5,
    borderRadius: 10,
  },
  btnActionEdit: {
    background: "#f0f9ff",
    borderColor: "#bae6fd",
    color: "#0284c7",
  },
  btnActionDelete: {
    background: "#fef2f2",
    borderColor: "#fecaca",
    color: "#dc2626",
  },
  tabContainer: {
    display: "flex",
    background: "#f1f5f9",
    padding: 5,
    borderRadius: 12,
    gap: 4,
  },
  tabButton: (isActive: boolean) => ({
    padding: "8px 22px",
    border: "none",
    borderRadius: 9,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 13.5,
    fontFamily: "inherit",
    background: isActive ? "#fff" : "transparent",
    color: isActive ? "#0f172a" : "#64748b",
    boxShadow: isActive ? "0 2px 8px rgba(0,0,0,0.08)" : "none",
    transition: "all 0.2s",
  }),
};